In [55]:
import numpy as np

In [8]:
a=np.array((100,101,102,103))
a

array([100, 101, 102, 103])

In [9]:
b=np.array([[1.,2.],[3.,4.]])
b

array([[ 1.,  2.],
       [ 3.,  4.]])

In [12]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [18]:
x=np.linspace(1,5,5)
x**2

array([  1.,   4.,   9.,  16.,  25.])

In [21]:
np.exp(-np.linspace(0.,2.,5))

array([ 1.        ,  0.60653066,  0.36787944,  0.22313016,  0.13533528])

In [22]:
np.exp(1)

2.7182818284590451

In [46]:
import math
print(format(math.pi,'.60f'))
import scipy
print(format(scipy.pi, '.60f'))

3.141592653589793115997963468544185161590576171875000000000000
3.141592653589793115997963468544185161590576171875000000000000


the pi in the python doesn't seem to be accurate enough

In [61]:
a=np.linspace(1.,6.,6)
# print(a.reshape(3,2))
print(a.reshape(3,2))
print(a.reshape(3,2).transpose())

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
[[ 1.  3.  5.]
 [ 2.  4.  6.]]
